language: node_js

node_js:
  - "node"

script:
  - npm test -- --maxWorkers=4

after_success: 'npm run coveralls'

cache:
  directories:
    - node_modules

deploy:
  provider: azure_web_apps
  verbose: true
