export const RECEIVE_ISSUES = "RECEIVE_ISSUES";
export const INVALIDATE_ISSUES = "INVALIDATE_ISSUES";
export const RECEIVE_USER_REPOSITORIES ="RECEIVE_USER_REPOSITORIES";
export const INVALIDATE_USER_REPOSITORIES = "INVALIDATE_USER_REPOSITORIES";