export const RECEIVE_ISSUES = "RECEIVE_ISSUES";
export const INVALIDATE_ISSUES = "INVALIDATE_ISSUES";
export const RECEIVE_USER_REPOSITORIES ="RECEIVE_USER_REPOSITORIES";
export const RECEIVE_ISSUES_ERROR = "RECEIVE_ISSUES_ERROR";
export const RECEIVE_ISSUES_PAGES_COUNT ="RECEIVE_ISSUES_PAGES_COUNT";
export const REQUEST_ISSUES = "REQUEST_ISSUES";